### ISSUE TITLE
App Logo and Configuration

### ISSUE THREAD

**Issue by nandababa** [24hourkirtan/audio-streaming-app#11]
I just selected the final 3 designers for our logo campaign http://99d.me/c/cq6p, which now have 3 days left to submit their final designs. I'd like to include our logo in the next alpha builds both for Android and iOS. I was wondering how we can make this logo configurable, though, so that if someone else uses the project can easily use their own logo.

Also the stream configuration and other things I might not be aware of should be probably configurable from a central config file and then also be documented accordingly. What are your thoughts on that?

**Comment by schmoofer** [comment]
Stream url configuration was addressed by 4ef659d726511ec02ac87842eaa08c420a105ff3
