### ISSUE TITLE
White strips in view - IOS version 0.8.1-beta

### ISSUE THREAD

**Issue by wkande** [24hourkirtan/audio-streaming-app#12]
iPhone 6s Plus only:

There is a white strip down the right side and across the bottom of the default view.  This does not appear to be an issue with iPhone 6s.

![img_0208](https://cloud.githubusercontent.com/assets/3522283/13614368/5b10cc46-e52d-11e5-84ce-83a0fc2fc658.PNG)

**Comment by schmoofer** [comment]
Fixed in f6e3774ea0de0fad75c7b2be648659629262a2e2
