### ISSUE TITLE
App Store warning (push notifications)  - IOS version 0.8.1-beta

### ISSUE THREAD

**Issue by wkande** [24hourkirtan/audio-streaming-app#15]
Got an email from the App Store which seems strange since the App does not use Push Notification. Should we add the entitlement or look for this mystery API in the App.

---------------------
Dear developer,

We have discovered one or more issues with your recent delivery for "Kirtan Radio". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Missing Push Notification Entitlement - Your app appears to include API used to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. See "Provisioning and Development" in the Local and Push Notification Programming Guide for more information. If your app does not use the Apple Push Notification service, no action is required. You may remove the API from future submissions to stop this warning. If you use a third-party framework, you may need to contact the developer for information on removing the API.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

Regards,

The App Store team

**Comment by schmoofer** [comment]
@wkande I'm not sure what's causing this. I'm opting for just including the "aps-environment" entitlement int eh provisioning profile.

**Comment by wkande** [comment]
I will add the entitlement if the warning continues.
