### ISSUE TITLE
No volume after app reactivation from lock screen  - IOS version 0.8.2

### ISSUE THREAD

**Issue by wkande** [24hourkirtan/audio-streaming-app#16]
The player will not start after locking the screen (with the app as the active app), unlocking the screen and hitting player button.

Steps to reproduce.

1. Launch the app.
2. Start the player.
3. As soon as music is heard stop the player.
4. Lock the screen.
5. Unlock the screen (app should be present).
6. Start the player.

At this point there is no music.

**Comment by schmoofer** [comment]
I'm not getting this behavior on my actual iPhone 5 device and the emulator. Can you verify this on the other devices/emulator?
