### ISSUE TITLE
Xcode project in "platforms/ios" missing

### ISSUE THREAD

**Issue by nandababa** [24hourkirtan/audio-streaming-app#17]
In the README it says under testing for iOS

Open the Xcode project in the "platforms/ios" project folder and deploy it to a test device or emulator

I remember that from initial versions, but the folder now seems to be gone. I'd like to reproduce an error in the simulator.

**Comment by schmoofer** [comment]
Did you follow the instructions in the Installation section of the README?

**Comment by nandababa** [comment]
I initially did, but looks like I started over and had to redo everything. It's now there, thanks.
