### ISSUE TITLE
Cannot resume playing after longer pause

### ISSUE THREAD

**Issue by nandababa** [24hourkirtan/audio-streaming-app#18]
In the iOS simulator I cannot resume playing after pausing for 60 seconds. Up to 40 seconds still works fine, though. This might be the same bug I recently decribed in an email when I'm on a mobile network and drive through a dead zone after which I cannot resume playing, but have to restart the app.

Using Xcod Version 7.3 (7D175) and Simulator Version 9.3 (SimulatorApp-645.9 CoreSimulator-209.19).

**Comment by wkande** [comment]
It may be possible this is related in some small way to Issue #16.

**Comment by nandababa** [comment]
Just tested this with v0.8.4 on Android and it resumes fine even after more than 60 secs auf pausing.  I was using a WiFi connection, so to be 100% sure it works OK, I'm going to test this on a mobile connection in the car and will re-open in case there's still an issue.
