### ISSUE TITLE
Support for iOS 8

### ISSUE THREAD

**Issue by nandababa** [24hourkirtan/audio-streaming-app#19]
Kavi Sivyer has volunteered as an alpha/beta tester and upon my invitation from iTunes Connect I got the following reponse:

> I just tried downloading the app, but it said that i need iOS 9 if i want to use it at all. But i haven’t updated because i don’t like the user interface of the new iOS 9 (and i know many other people who have done the same thing).
> 
> So i don’t know if there is a way of making the app also available to those with previous iOS?
> 
> If not then its no problem, but just a thought so that you can capture those who haven’t updated also.

Not sure if this really makes sense, but how easy or hard would it be to also support iOS 8?

**Comment by wkande** [comment]
All we need is to have David confirm he does not have any need to IOS 9.
As far as resetting the deployment to 8.x it is easy. Of course a decision
on which minimum 8.x is needed.  Will we go as low as 8.0?

**Comment by schmoofer** [comment]
I don't believe the app requires iOS 9

**Comment by wkande** [comment]
Great I will redeploy when I get back using IOS 8.0.
