### ISSUE TITLE
Node.js 4,5 or 6?

### ISSUE THREAD

**Issue by nandababa** [24hourkirtan/audio-streaming-app#20]
The readme install sections says to first install Node.js 4 (Node 5 does not work at the moment!). I recently installed everything from scratch and have Node v6.2.1. Not sure if I have to use v4.4.5 LTS instead in order to get this to work? What actually happened to Node.js 5?

**Comment by wkande** [comment]
6x should work but I have not tested it with the APIs. I just used 4x LTS
versions because they are know to be stable. 5x had a short life that went
no where and I believe that was the intent. 6x will be the next LTS version
so we should be OK.

**Comment by frissonlabs** [comment]
Now works with the latest version of NodeJS
