### ISSUE TITLE
Radio only mode configuration

### ISSUE THREAD

**Issue by nandababa** [24hourkirtan/audio-streaming-app#27]
Some people might only want to use the app to stream their radio station without any playlist mode stuff. In order to avoid developing 2 separate versions of the app, we could add a configuration that has playlist mode enabled by default, but let users disable it so that the app gets build without the additional menu items.

**Comment by nandababa** [comment]
Not sure if this type of configuration belongs into config.xml or anywhere else. The idea is that if you build the app with radio-only mode, the playlist menu items will not be visible in the app. I hope that makes it more clear.

**Comment by schmoofer** [comment]
Does this mean you'll release two separate apps in the store?

**Comment by nandababa** [comment]
No, for us all features make sense, but others might only be interested in the regular streaming. That's why I want to offer the possibility to hide or exclude the playlist functionality.

**Comment by schmoofer** [comment]
Just added a preference item with the name "radio-only" in "config.xml" where you can specify "true" to have it build in radio-only mode or "false" to have full functionality, including playlists.
