### ISSUE TITLE
Not play streaming audio on Android

### ISSUE THREAD

**Issue by joseaperez** [24hourkirtan/audio-streaming-app#28]
The application with ionic 2.0 (which is supposed to be fully backward compatible with earlier versions) does not play streaming audio on any android. I tested in many devices and all give the same error message in the log:
Uncaught ReferenceError: Media is not defined
services.js: 17 Object

Any solution?

**Comment by schmoofer** [comment]
I have not tested the app with Ionic 2.0 but you can pull the latest version which has some fixes and see if that takes care of the issue.

**Comment by fdambrosio** [comment]
Hi, it works with ionic 2 & angular 2?

**Comment by richcaputo** [comment]
Same issue here. It is working on iOS but android will not play music. Has there been a fix for this?

**Comment by euphonialabs** [comment]
@richcaputo Can you provide the console output in Chrome inspector? I have it working so I'm not sure what the problem is

**Comment by go2hyder** [comment]
Getting same error

`Uncaught ReferenceError: Media is not defined
    at Object.init (services.js:64)
    at Channel.<anonymous> (radio.js:40)
    at Channel.fire (cordova.js:822)
    at cordova.js:231`
