### ISSUE TITLE
Ionic and Splash resource changes to config.xml

### ISSUE THREAD

**Issue by wkande** [24hourkirtan/audio-streaming-app#4]
When I run ionic resources the config.xml gets updated in that the Android splash landscape elements get removed. The app builds and runs.  Would it help to run ionic resources and push them into GitHub so the binaries are set and the config.xml is properly set as well.  This would help when cloning the repository to build and run. Also this would prevent the constant need to push and pull changes to the config.xml file every time someone runs ionic resources.

I wonder if the difference might be that the resources have been created on a PC and in my case they have to be rerun on Mac to create a build. Of course that does not answer the questions as to why the config.xml file drops the landscape elements.

**Comment by schmoofer** [comment]
Do we need landscape elements for this app? It looks more appropriate as portrait-only. It might be dropping the landscape elements because I declared that preference in the config.xml:

<preference name="orientation" value="portrait"/>

**Comment by wkande** [comment]
I agree, we can aways add it back in. Right now the config.xml file contains the landscape elements. When I run ionic resources they are of course removed.  When I do the next alpha build and change the version in config.xml I will commit the file with the version and the removal of the landscape (android) elements.

**Comment by nandababa** [comment]
I don't think we need landscape elements. Neither Spotify nor TuneIn offer landscape mode.

**Comment by schmoofer** [comment]
I added the instruction to manually generate the appropriate resources via "ionic resources" so this should address this issue via commit #227777b6f6f351b45bcbc5b1c0f121947722143b
