### ISSUE TITLE
Pause button fails to stop player

### ISSUE THREAD

**Issue by wkande** [24hourkirtan/audio-streaming-app#9]
This catch is regarding the install on a Samsung S4 running the latest alpha release 0.8.0. This issue was also reproduced by doing a build and run from CLI to a connected ADB device of the current source code at tag 0.8.0. 

The **Pause** button does not seem to stop the play process if selected during the buffer time the play button is implementing.

To reproduce
* After the app open press the **Play** button
* After a few seconds but before music plays press the **Pause** button
* Wait up to 20 seconds and music will play even though the **Pause** button has been pressed

Repeated attempts to stop the music by pressing the **Play** button fail, the music keeps playing.

**Comment by schmoofer** [comment]
Fixed in 5dcc9951e681458f66ef87a9a02d8ac58902b979
